function json10rugvs() {

  const json10rugvs=[
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2010/65letwin.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2010/avers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2010",
    "text": "Официальная эмблема 65-летия Победы",
    "price": "200",
    "count": "1",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-1",
    "datayear": "data-year = year-1",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0001"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2011/50letfly.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2011/avers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2011",
    "text": "50 лет первого полета человека в космос",
    "price": "90",
    "count": "5",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-1",
    "datayear": "data-year = year-2",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0010"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2011/elna.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2011/avers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2011",
    "text": "Ельня",
    "price": "150",
    "count": "1",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-2",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0009"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2011/elec.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2011/avers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2011",
    "text": "Елец",
    "price": "190",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-2",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0008"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2011/rzhev.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2011/avers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2011",
    "text": "Ржев",
    "price": "100",
    "count": "1",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-2",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0007"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2011/malgobek.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2011/avers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2011",
    "text": "Малгобек",
    "price": "100",
    "count": "2",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-2",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0006"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2011/vladikavkaz.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2011/avers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2011",
    "text": "Владикавказ",
    "price": "100",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-2",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0005"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2011/kursk.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2011/avers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2011",
    "text": "Курск",
    "price": "100",
    "count": "1",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-2",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0003"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2011/orel.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2011/avers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2011",
    "text": "Орёл",
    "price": "150",
    "count": "1",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-2",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0004"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2011/belgorod.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2011/avers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2011",
    "text": "Белгород",
    "price": "140",
    "count": "2",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-2",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0002"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2012/1150letrf.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2012/avers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2012",
    "text": "1150-летие зарождения российской государственности",
    "price": "70",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-1",
    "datayear": "data-year = year-3",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0011"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2012/1812war.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2012/avers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2012",
    "text": "200-летие победы России в Отечественной войне 1812 года",
    "price": "90",
    "count": "1",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-5",
    "datayear": "data-year = year-3",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0017"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2012/dmitrov.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2012/avers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2012",
    "text": "Дмитров",
    "price": "60",
    "count": "1",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-3",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0020"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2012/velnovgorod.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2012/avers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2012",
    "text": "Великий Новгород",
    "price": "19",
    "count": "1",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-3",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0019"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2012/velluki.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2012/avers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2012",
    "text": "Великие Луки",
    "price": "70",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-3",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0018"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2012/velluki.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2012/avers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2012",
    "text": "Туапсе",
    "price": "70",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-3",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0016"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2012/rostovnadonu.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2012/avers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2012",
    "text": "Ростов-на-Дону",
    "price": "80",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-3",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0015"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2012/polar.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2012/avers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2012",
    "text": "Полярный",
    "price": "90",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-3",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0014"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2012/luga.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2012/avers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2012",
    "text": "Луга",
    "price": "90",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-3",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0013"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2012/voronezhjpg.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2012/avers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2012",
    "text": "Воронеж",
    "price": "90",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-3",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0012"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2013/constitution.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2013/avers1.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2013",
    "text": "20-летие принятия Конституции Российской Федерации",
    "price": "40",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-1",
    "datayear": "data-year = year-4",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0032"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2013/70yearstalingrad.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2013/avers2.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2013",
    "text": "70-летие разгрома советскими войсками немецко-фашистских войск в Сталинградской битве",
    "price": "40",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-1",
    "datayear": "data-year = year-4",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0025"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2013/universiadeemblem.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2013/avers3.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2013",
    "text": "Логотип и эмблема Универсиады",
    "price": "70",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-1",
    "datayear": "data-year = year-4",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0021"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2013/universiadatalisman.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2013/avers3.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2013",
    "text": "Талисман Универсиады",
    "price": "70",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-1",
    "datayear": "data-year = year-4",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0022"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2013/bryansk.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2013/avers3.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2013",
    "text": "Брянск",
    "price": "40",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-4",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0031"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2013/volokalamsk.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2013/avers3.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2013",
    "text": "Волоколамск",
    "price": "40",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-4",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0030"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2013/arhangelsk.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2013/avers3.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2013",
    "text": "Архангельск",
    "price": "40",
    "count": "1",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-4",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0029"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2013/kozelsk.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2013/avers3.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2013",
    "text": "Козельск",
    "price": "40",
    "count": "1",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-4",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0028"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2013/pskov.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2013/avers3.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2013",
    "text": "Псков",
    "price": "40",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-4",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0027"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2013/narofominsk.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2013/avers3.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2013",
    "text": "Наро-Фоминск",
    "price": "40",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-4",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0026"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2013/kronschtadt.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2013/avers3.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2013",
    "text": "Кронштадт",
    "price": "40",
    "count": "1",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-4",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0024"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2013/vyazma.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2013/avers3.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2013",
    "text": "Вязьма",
    "price": "40",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-4",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0023"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2014/crimea.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2014/avers1.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2014",
    "text": "Вхождение в состав Р. Ф. Респ. Крым и Севастополя",
    "price": "60",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-1",
    "datayear": "data-year = year-5",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0040"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2014/sevastopol.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2014/avers1.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2014",
    "text": "Вхождение в состав Р. Ф. Респ. Крым и города Севастополя",
    "price": "50",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-1",
    "datayear": "data-year = year-5",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0041"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2014/kolpino.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2014/avers3.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2014",
    "text": "Колпино",
    "price": "50",
    "count": "1",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-5",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0042"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2014/anapa.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2014/avers3.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2014",
    "text": "Анапа",
    "price": "50",
    "count": "1",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-5",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0039"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2014/tver.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2014/avers3.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2014",
    "text": "Тверь",
    "price": "50",
    "count": "1",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-5",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0038"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2014/tihvin.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2014/avers3.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2014",
    "text": "Тихвин",
    "price": "50",
    "count": "1",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-5",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0037"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2014/vladivostok.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2014/avers3.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2014",
    "text": "Владивосток",
    "price": "50",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-5",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0036"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2014/staroskol.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2014/avers2.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2014",
    "text": "Старый Оскол",
    "price": "50",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-5",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0035"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2014/vyborg.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2014/avers3.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2014",
    "text": "Выборг",
    "price": "50",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-5",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0034"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2014/nalchik.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2014/avers3.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2014",
    "text": "Нальчик",
    "price": "50",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-5",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0033"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2015/taganrog.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2015/avers1.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2015",
    "text": "Таганрог",
    "price": "120",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-6",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0048"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2015/petropavlovskamchatsk.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2015/avers1.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2015",
    "text": "Петропавловск-Камчатский",
    "price": "120",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-6",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0049"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2015/maloyaroslavec.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2015/avers1.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2015",
    "text": "Малоярославец",
    "price": "50",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-6",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0050"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2015/mozaisk.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2015/avers1.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2015",
    "text": "Можайск",
    "price": "50",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-6",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0051"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2015/habarovsk.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2015/avers1.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2015",
    "text": "Хабаровск",
    "price": "75",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-6",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0047"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2015/kalachdon.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2015/avers1.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2015",
    "text": "Калач-на-Дону",
    "price": "90",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-6",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0044"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2015/kovrov.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2015/avers1.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2015",
    "text": "Ковров",
    "price": "50",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-6",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0045"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2015/lomonosov.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2015/avers1.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2015",
    "text": "Ломоносов",
    "price": "70",
    "count": "1",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-6",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0046"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2015/groznyy.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2015/avers2.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2015",
    "text": "Грозный",
    "price": "40",
    "count": "1",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-6",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0043"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2016/feodosiya.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2016/avers1.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2016",
    "text": "Феодосия",
    "price": "50",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-7",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0054"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2016/petrozavodsk.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2016/avers1.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2016",
    "text": "Петрозаводск",
    "price": "20",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-7",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0055"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2016/gatchina.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2016/avers1.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2016",
    "text": "Гатчина",
    "price": "40",
    "count": "1",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-7",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0053"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2016/starayarussa.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2016/avers2.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "10 рублей 2016",
    "text": "Старая Русса",
    "price": "50",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-7",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0052"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2018/winterunivesiade.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2018/avers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2018",
    "text": "ХХIХ Всемирная зимняя универсиада 2019 года в г. Красноярске",
    "price": "45",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-1",
    "datayear": "data-year = year-9",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0061"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2018/winteruniversiadatalisman.jpg",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2018/avers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2018",
    "text": "ХХIХ Всемирная зимняя универсиада 2019 года в г. Красноярске",
    "price": "45",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-1",
    "datayear": "data-year = year-9",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0062"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2020/transport.png",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2020/avers.png",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2020",
    "text": "Работник транспортной сферы",
    "price": "110",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-4",
    "datayear": "data-year = year-11",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0071"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2020/stalevar.png",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2020/avers.png",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2020",
    "text": "Работник металлургической промышленности",
    "price": "110",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-4",
    "datayear": "data-year = year-11",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0068"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2021/borovichi.png",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2021/avers.png",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2021",
    "text": "Боровичи",
    "price": "190",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-12",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0075"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2021/ekaterinburg.png",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2021/avers.png",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2021",
    "text": "Екатеринбург",
    "price": "190",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-12",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0076"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2021/ivanovo.png",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2021/avers.png",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2021",
    "text": "Иваново",
    "price": "190",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-12",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0077"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2021/omsk.png",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2021/avers.png",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2021",
    "text": "Омск",
    "price": "190",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-12",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0078"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2021/neftegaz.png",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2021/avers.png",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2021",
    "text": "Работник нефтегазовой отрасли",
    "price": "95",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-4",
    "datayear": "data-year = year-12",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0073"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2022/izevsk.png",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2022/avers.png",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2022",
    "text": "Ижевск",
    "price": "90",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-13",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0079"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2022/irkutsk.png",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2022/avers.png",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2022",
    "text": "Иркутск",
    "price": "90",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-13",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0080"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2022/kazan.png",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2022/avers.png",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2022",
    "text": "Казань",
    "price": "90",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-13",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0081"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2022/magnitogorsk.png",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2022/avers.png",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2022",
    "text": "Магнитогорск",
    "price": "90",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-13",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0082"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2022/miner.png",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2022/avers.png",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2022",
    "text": "Работник добывающей промышленности",
    "price": "90",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-4",
    "datayear": "data-year = year-13",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0086"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2023/niznovgorod.png",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2023/avers.png",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2023",
    "text": "Нижний Новгород",
    "price": "95",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-14",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0087"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2023/niztagil.png",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2023/avers.png",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2023",
    "text": "Нижний Тагил",
    "price": "95",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-14",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0088"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2023/novokuznetsk.png",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2023/avers.png",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2023",
    "text": "Новокузнецк",
    "price": "95",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-14",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0089"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2023/novosibirsk.png",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2023/avers.png",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2023",
    "text": "Новосибирск",
    "price": "95",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-14",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0090"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2023/stroitel.png",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2023/avers.png",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2023",
    "text": "Работник строительной сферы",
    "price": "90",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-4",
    "datayear": "data-year = year-14",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0091"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2024/perm.png",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2024/avers.png",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2024",
    "text": "Пермь",
    "price": "190",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-15",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0096"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2024/samara.png",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2024/avers.png",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2024",
    "text": "Самара",
    "price": "190",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-15",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0097"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2024/saratov.png",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2024/avers.png",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2024",
    "text": "Саратов",
    "price": "190",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-15",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0098"
  },
  {
    "img": "./img/coins/russia/yubilee/10rugvs/2024/tomsk.png",
    "imgrev": "./img/coins/russia/yubilee/10rugvs/2024/avers.png",
    "md": "./img/other/mmd.jpg",
    "title": "10 рублей 2024",
    "text": "Томск",
    "price": "190",
    "count": "0",
    "info": "В наличии",
    "color": "card__off",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-15",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5714-0099"
  }
] 
  return json10rugvs;
}
export default json10rugvs;