function json1kopru(){

  const json1kopru=[
    {
      "img": "./img/coins/russia/regular/1kop/1997/97_1k_M.jpg",
      "imgrev": "./img/coins/russia/regular/1kop/1997/97_1k_M_R.jpg",
      "md": "./img/other/m.png",
      "title": "1 копейка 1997",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/1k/"
    },
    {
      "img": "./img/coins/russia/regular/1kop/1997/97_1k_S.jpg",
      "imgrev": "./img/coins/russia/regular/1kop/1997/97_1k_S_R.jpg",
      "md": "./img/other/sp.png",
      "title": "1 копейка 1997",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/1k/"
    },
    {
      "img": "./img/coins/russia/regular/1kop/1998/98_1k_M.jpg",
      "imgrev": "./img/coins/russia/regular/1kop/1998/98_1k_M_R.jpg",
      "md": "./img/other/m.png",
      "title": "1 копейка 1998",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/1k/"
    },
    {
      "img": "./img/coins/russia/regular/1kop/1998/98_1k_S.jpg",
      "imgrev": "./img/coins/russia/regular/1kop/1998/98_1k_S_R.jpg",
      "md": "./img/other/sp.png",
      "title": "1 копейка 1998",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/1k/"
    },
    {
      "img": "./img/coins/russia/regular/1kop/1999/99_1k_M.jpg",
      "imgrev": "./img/coins/russia/regular/1kop/1999/99_1k_M_R.jpg",
      "md": "./img/other/m.png",
      "title": "1 копейка 1999",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "80",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/1k/"
    },
    {
      "img": "./img/coins/russia/regular/1kop/1999/99_1k_S.jpg",
      "imgrev": "./img/coins/russia/regular/1kop/1999/99_1k_S_R.jpg",
      "md": "./img/other/sp.png",
      "title": "1 копейка 1999",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "40",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/1k/"
    },
    {
      "img": "./img/coins/russia/regular/1kop/2000/00_1k_M.jpg",
      "imgrev": "./img/coins/russia/regular/1kop/2000/00_1k_M_R.jpg",
      "md": "./img/other/m.png",
      "title": "1 копейка 2000",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/1k/"
    },
    {
      "img": "./img/coins/russia/regular/1kop/2000/00_1k_S.jpg",
      "imgrev": "./img/coins/russia/regular/1kop/2000/00_1k_S_R.jpg",
      "md": "./img/other/sp.png",
      "title": "1 копейка 2000",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/1k/"
    },
    {
      "img": "./img/coins/russia/regular/1kop/2001/01_1k_M.jpg",
      "imgrev": "./img/coins/russia/regular/1kop/2001/01_1k_M_R.jpg",
      "md": "./img/other/m.png",
      "title": "1 копейка 2001",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/1k/"
    },
    {
      "img": "./img/coins/russia/regular/1kop/2001/01_1k_S.jpg",
      "imgrev": "./img/coins/russia/regular/1kop/2001/01_1k_S_R.jpg",
      "md": "./img/other/sp.png",
      "title": "1 копейка 2001",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/1k/"
    },
    {
      "img": "./img/coins/russia/regular/1kop/2002/02_1k_M.jpg",
      "imgrev": "./img/coins/russia/regular/1kop/2002/02_1k_M_R.jpg",
      "md": "./img/other/m.png",
      "title": "1 копейка 2002",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/1k/"
    },
    {
      "img": "./img/coins/russia/regular/1kop/2002/02_1k_S.jpg",
      "imgrev": "./img/coins/russia/regular/1kop/2002/02_1k_S_R.jpg",
      "md": "./img/other/sp.png",
      "title": "1 копейка 2002",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/1k/"
    },
    {
      "img": "./img/coins/russia/regular/1kop/2003/03_1k_M.jpg",
      "imgrev": "./img/coins/russia/regular/1kop/2003/03_1k_M_R.jpg",
      "md": "./img/other/m.png",
      "title": "1 копейка 2003",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/1k/"
    },
    {
      "img": "./img/coins/russia/regular/1kop/2003/03_1k_S.jpg",
      "imgrev": "./img/coins/russia/regular/1kop/2003/03_1k_S_R.jpg",
      "md": "./img/other/sp.png",
      "title": "1 копейка 2003",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/1k/"
    },
    {
      "img": "./img/coins/russia/regular/1kop/2004/04_1k_M.jpg",
      "imgrev": "./img/coins/russia/regular/1kop/2004/04_1k_M_R.jpg",
      "md": "./img/other/m.png",
      "title": "1 копейка 2004",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/1k/"
    },
    {
      "img": "./img/coins/russia/regular/1kop/2004/04_1k_S.jpg",
      "imgrev": "./img/coins/russia/regular/1kop/2004/04_1k_S_R.jpg",
      "md": "./img/other/sp.png",
      "title": "1 копейка 2004",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/1k/"
    },
    {
      "img": "./img/coins/russia/regular/1kop/2005/05_1k_M.jpg",
      "imgrev": "./img/coins/russia/regular/1kop/2005/05_1k_M_R.jpg",
      "md": "./img/other/m.png",
      "title": "1 копейка 2005",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "40",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/1k/"
    },
    {
      "img": "./img/coins/russia/regular/1kop/2005/05_1k_S.jpg",
      "imgrev": "./img/coins/russia/regular/1kop/2005/05_1k_S_R.jpg",
      "md": "./img/other/sp.png",
      "title": "1 копейка 2005",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/1k/"
    },
    {
      "img": "./img/coins/russia/regular/1kop/2006/06_1k_M.jpg",
      "imgrev": "./img/coins/russia/regular/1kop/2006/06_1k_M_R.jpg",
      "md": "./img/other/m.png",
      "title": "1 копейка 2006",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "40",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/1k/"
    },
    {
      "img": "./img/coins/russia/regular/1kop/2006/06_1k_S.jpg",
      "imgrev": "./img/coins/russia/regular/1kop/2006/06_1k_S_R.jpg",
      "md": "./img/other/sp.png",
      "title": "1 копейка 2006",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/1k/"
    },
    {
      "img": "./img/coins/russia/regular/1kop/2007/07_1k_M.jpg",
      "imgrev": "./img/coins/russia/regular/1kop/2007/07_1k_M_R.jpg",
      "md": "./img/other/m.png",
      "title": "1 копейка 2007",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "40",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/1k/"
    },
    {
      "img": "./img/coins/russia/regular/1kop/2007/07_1k_S.jpg",
      "imgrev": "./img/coins/russia/regular/1kop/2007/07_1k_S_R.jpg",
      "md": "./img/other/sp.png",
      "title": "1 копейка 2007",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/1k/"
    },
    
  ]
  return json1kopru;
}

export default json1kopru;