function json25ru(){
  const json25ru =[
  {
    "img": "./img/coins/russia/yubilee/25ru/2011/sochi.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2011/revers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "text": "Эмблема Игр",
    "title": "25 рублей 2011",
    "price": "190",
    "count": "5",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "series-5",
    "datayear": "data-year = year-1",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0001"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2011/sochicolor.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2011/revers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "text": "Эмблема Игр",
    "title": "25 рублей 2011",
    "price": "838",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "dataseries": "series-5",
    "datayear": "data-year = year-1",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0002"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2012/talisman.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2012/revers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "text": "Талисманы и Эмблема Игр",
    "title": "25 рублей 2012",
    "price": "89",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "dataseries": "data-series = series-5",
    "datayear": "data-year = year-2",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0003"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2012/talismancolor.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2012/revers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "text": "Талисманы и Эмблема Игр",
    "title": "25 рублей 2012",
    "price": "756",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-5",
    "datayear": "data-year = year-2",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0004"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2013/sochi.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2013/revers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "25 рублей 2013",
    "text": "Эмблема XXII Олимпийских зимних игр Сочи",
    "price": "70",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-5",
    "datayear": "data-year = year-3",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0009"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2013/talisman.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2013/revers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "25 рублей 2013",
    "text": "Талисманы и эмблема XXII Олимпийских зимних игр Сочи 2014",
    "price": "90",
    "count": "1",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-5",
    "datayear": "data-year = year-3",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0010"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2013/luchik.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2013/revers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "25 рублей 2013",
    "text": "Талисманы и логотип XI Паралимпийских зимних игр Сочи ",
    "price": "70",
    "count": "1",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-5",
    "datayear": "data-year = year-3",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0011"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2013/estafeta.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2013/revers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "25 рублей 2013",
    "text": "Эстафета Олимпийского огня Сочи",
    "price": "70",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-5",
    "datayear": "data-year = year-3",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0007"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2013/estafetacolor.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2013/revers.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "25 рублей 2013",
    "text": "Эстафета Олимпийского огня Сочи",
    "price": "950",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-5",
    "datayear": "data-year = year-3",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0008"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2013/luchik2013.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2013/revers13.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "25 рублей 2013",
    "text": "Талисманы и логотип XI Паралимпийских зимних игр Сочи",
    "price": "70",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-5",
    "datayear": "data-year = year-3",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0005"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2013/luchikcolor.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2013/revers13.jpg",
    "md": "./img/other/spmd-m.jpg",
    "title": "25 рублей 2013",
    "text": "Талисманы и логотип XI Паралимпийских зимних игр Сочи",
    "price": "950",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-5",
    "datayear": "data-year = year-3",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0006"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2016/worldcup.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2016/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2016",
    "text": "Чемпионат мира по футболу FIFA 2018 в России",
    "price": "50",
    "count": "1",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-4",
    "datayear": "data-year = year-4",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0013"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2016/worldcupcolor.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2016/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2016",
    "text": "Чемпионат мира по футболу FIFA 2018 в России",
    "price": "1500",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-4",
    "datayear": "data-year = year-4",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0013"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2017/children.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2017/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2017",
    "text": "Дари добро детям",
    "price": "400",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-1",
    "datayear": "data-year = year-5",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0017"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2017/carabin.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2017/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2017",
    "text": "Чемпионат мира по практической стрельбе из карабина",
    "price": "5500",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-1",
    "datayear": "data-year = year-5",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0014"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2017/puh.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2017/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2017",
    "text": "Винни Пух",
    "price": "2990",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-5",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0022"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2017/puhcolor.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2017/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2017",
    "text": "Винни Пух",
    "price": "25000",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-5",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0023"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2017/triwaior.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2017/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2017",
    "text": "Три богатыря",
    "price": "2990",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-5",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0020"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2017/triwariorcolor.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2017/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2017",
    "text": "Три богатыря",
    "price": "27000",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-5",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0021"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2017/zabivaka.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2017/revers18.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2017",
    "text": "Чемпионат мира по футболу FIFA 2018 в России",
    "price": "70",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-4",
    "datayear": "data-year = year-5",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0018"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2017/zabivakacolor.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2017/revers18.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2017",
    "text": "Чемпионат мира по футболу FIFA 2018 в России",
    "price": "790",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-4",
    "datayear": "data-year = year-5",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0019"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2017/worldcup.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2017/revers18.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2017",
    "text": "Чемпионат мира по футболу FIFA 2018 в России",
    "price": "60",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-4",
    "datayear": "data-year = year-5",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0015"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2017/worldcupcolor.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2017/revers18.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2017",
    "text": "Чемпионат мира по футболу FIFA 2018 в России",
    "price": "990",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-4",
    "datayear": "data-year = year-5",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0016"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2018/const.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2018/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2018",
    "text": "25-летие принятия Конституции Р. Ф.",
    "price": "150",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-1",
    "datayear": "data-year = year-6",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0027"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2018/armygame.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2018/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2018",
    "text": "Армейские международные игры",
    "price": "490",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-1",
    "datayear": "data-year = year-6",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0024"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2018/nupogodi.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2018/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2018",
    "text": "Ну, погоди!",
    "price": "3600",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-6",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0025"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2018/nupogodicolor.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2018/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2018",
    "text": "Ну, погоди!",
    "price": "25000",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-6",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0026"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2019/leningrad.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2019/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2019",
    "text": "75-летие полного освобождения Ленинграда от фашистской блокады",
    "price": "150",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-1",
    "datayear": "data-year = year-7",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0028"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2019/grabin.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2019/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2019",
    "text": "Конструктор оружия В.Г. Грабин",
    "price": "35",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-7",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0033"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2019/kotin.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2019/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2019",
    "text": "Конструктор оружия Ж.Я. Котин",
    "price": "35",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-7",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0034"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2019/koshkin.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2019/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2019",
    "text": "Конструктор оружия М.И. Кошкин",
    "price": "35",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-7",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0035"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2019/malinin.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2019/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2019",
    "text": "Конструктор оружия Б.М. Малинин",
    "price": "35",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-7",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0036"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2019/petlyakov.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2019/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2019",
    "text": "Конструктор оружия В.М. Петляков",
    "price": "35",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-7",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0037"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2019/petrov.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2019/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2019",
    "text": "Конструктор оружия Ф.Ф. Петров",
    "price": "35",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-7",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0038"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2019/polikarpov.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2019/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2019",
    "text": "Конструктор оружия Н.Н. Поликарпов",
    "price": "35",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-7",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0039"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2019/simonov.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2019/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2019",
    "text": "Конструктор оружия С.Г. Симонов",
    "price": "35",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-7",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0040"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2019/shpagin.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2019/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2019",
    "text": "Конструктор оружия Г.С. Шпагин",
    "price": "35",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-7",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0041"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2019/moroz.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2019/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2019",
    "text": "Дед Мороз и лето",
    "price": "1390",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-7",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0031"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2019/morozcolor.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2019/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2019",
    "text": "Дед Мороз и лето",
    "price": "29700",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-7",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0032"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2019/muzic.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2019/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2019",
    "text": "Бременские музыканты",
    "price": "1890",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-7",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0029"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2019/miziccolor.jpg",
    "imgrev": "./img/coins/russia/yubilee/25ru/2019/revers.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2019",
    "text": "Бременские музыканты",
    "price": "29500",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-7",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0030"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2020/25RU20-1.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2020/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2020",
    "text": "Памятная монета, посвященная самоотверженному труду медицинских работников",
    "price": "60",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-1",
    "datayear": "data-year = year-8",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0054"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2020/25RU20-2.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2020/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2020",
    "text": "Конструктор оружия С.В. Ильюшин",
    "price": "190",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-8",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0047"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2020/25RU20-3.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2020/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2020",
    "text": "Конструктор оружия С.А. Лавочкин",
    "price": "190",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-8",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0048"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2020/25RU20-4.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2020/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2020",
    "text": "Конструктор оружия М.Н. Логинов",
    "price": "190",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-8",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0049"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2020/25RU20-5.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2020/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2020",
    "text": "Конструктор оружия А.Н. Туполев",
    "price": "190",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-8",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0050"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2020/25RU20-6.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2020/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2020",
    "text": "Конструктор оружия А.С. Яковлев",
    "price": "190",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-8",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0051"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2020/25RU20-7.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2020/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2020",
    "text": "Конструктор оружия П.М. Горюнов",
    "price": "190",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-8",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0042"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2020/25RU20-8.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2020/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2020",
    "text": "Конструктор оружия Л.Л. Ермаш",
    "price": "190",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-8",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0043"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2020/25RU20-9.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2020/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2020",
    "text": "Конструктор оружия А.И. Маслов",
    "price": "190",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-8",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0044"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2020/25RU20-10.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2020/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2020",
    "text": "Конструктор оружия А.И. Судаев",
    "price": "190",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-8",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0045"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2020/25RU20-11.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2020/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2020",
    "text": "Конструктор оружия Ф.В. Токарев",
    "price": "190",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-3",
    "datayear": "data-year = year-8",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0046"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2020/25RU20-12.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2020/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2020",
    "text": "Крокодил Гена",
    "price": "570",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-8",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0055"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2020/25RU20-13.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2020/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2020",
    "text": "Крокодил Гена",
    "price": "5700",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-8",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0056"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2020/25RU20-14.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2020/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2020",
    "text": "Барбоскины",
    "price": "370",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-8",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0052"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2020/25RU20-15.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2020/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2020",
    "text": "Барбоскины",
    "price": "2600",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-8",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0052"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2021/25RU21-1.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2021/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2021",
    "text": "Творчество Юрия Никулина",
    "price": "230",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-1",
    "datayear": "data-year = year-9",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0063"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2021/25RU21-2.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2021/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2021",
    "text": "Творчество Юрия Никулина",
    "price": "2590",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-1",
    "datayear": "data-year = year-9",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0064"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2021/25RU21-3.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2021/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2021",
    "text": "60-летие первого полета человека в космос",
    "price": "450",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-1",
    "datayear": "data-year = year-9",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0057"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2021/25RU21-4.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2021/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2021",
    "text": "60-летие первого полета человека в космос",
    "price": "1760",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-1",
    "datayear": "data-year = year-9",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0058"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2021/25RU21-5.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2021/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2021",
    "text": "Маша и Медведь",
    "price": "370",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-9",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0061"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2021/25RU21-6.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2021/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2021",
    "text": "Маша и Медведь",
    "price": "2990",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-9",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0062"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2021/25RU21-7.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2021/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2021",
    "text": "Умка",
    "price": "340",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-9",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0059"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2021/25RU21-8.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2021/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2021",
    "text": "Умка",
    "price": "2850",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-9",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0060"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2022/25RU22-1.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2022/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2022",
    "text": "Веселая карусель № 1",
    "price": "395",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-10",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0067"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2022/25RU22-2.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2022/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2022",
    "text": "Веселая карусель № 1",
    "price": "2490",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-10",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0068"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2022/25RU22-3.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2022/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2022",
    "text": "Иван Царевич и Серый Волк",
    "price": "350",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-10",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0065"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2022/25RU22-4.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2022/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2022",
    "text": "Иван Царевич и Серый Волк",
    "price": "1990",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-10",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0066"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2023/25RU23-1.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2023/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2023",
    "text": "Аленький цветочек",
    "price": "285",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-11",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5715-0002"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2023/25RU23-2.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2023/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2023",
    "text": "Аленький цветочек",
    "price": "1850",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-11",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0070"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2023/25RU23-3.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2023/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2023",
    "text": "Смешарики",
    "price": "300",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-11",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5715-0001"
  },
  {
    "img": "./img/coins/russia/yubilee/25ru/2023/25RU23-4.png",
    "imgrev": "./img/coins/russia/yubilee/25ru/2023/revers.png",
    "md": "./img/other/mmd.jpg",
    "title": "25 рублей 2023",
    "text": "Смешарики",
    "price": "3690",
    "count": "0",
    "info": "Отсутствует",
    "color": "card__off",
    "data": "data-absent = absent",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-11",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5015-0069"
  }

];
  return json25ru;
}
export default json25ru;