function json2ruyub(){
  const json2ruyub=[
    {
      "img": "./img/coins/russia/yubilee/2ru/2000/2RU00-1.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2000/2RU00-8.jpg",
      "md": "./img/other/spmd-m.jpg",
      "title": "2 рубля 2000",
      "text": "Ленинград",
      "desc":  "Стоимость:",
      "price": "199",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-3",
      "datayear": "data-year = year-1",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5010-0001"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2000/2RU00-2.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2000/2RU00-8.jpg",
      "md": "./img/other/spmd-m.jpg",
      "title": "2 рубля 2000",
      "text": "Сталинград",
      "desc":  "Стоимость:",
      "price": "139",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-3",
      "datayear": "data-year = year-1",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5010-0002"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2000/2RU00-3.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2000/2RU00-8.jpg",
      "md": "./img/other/spmd-m.jpg",
      "title": "2 рубля 2000",
      "text": "Новороссийск",
      "desc":  "Стоимость:",
      "price": "129",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-3",
      "datayear": "data-year = year-1",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5010-0004"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2000/2RU00-4.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2000/2RU00-9.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "2 рубля 2000",
      "text": "Тула",
      "desc":  "Стоимость:",
      "price": "119",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-3",
      "datayear": "data-year = year-1",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5010-0005"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2000/2RU00-5.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2000/2RU00-9.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "2 рубля 2000",
      "text": "Мурманск",
      "desc":  "Стоимость:",
      "price": "119",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-3",
      "datayear": "data-year = year-1",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5010-0007"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2000/2RU00-6.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2000/2RU00-9.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "2 рубля 2000",
      "text": "Москва",
      "desc":  "Стоимость:",
      "price": "139",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-3",
      "datayear": "data-year = year-1",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5010-0003"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2000/2RU00-7.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2000/2RU00-9.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "2 рубля 2000",
      "text": "Смоленск",
      "desc":  "Стоимость:",
      "price": "119",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-3",
      "datayear": "data-year = year-1",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5010-0006"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2001/gagarin.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2001/2RU01-2.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "2 рубля 2001",
      "text": "40-летие космического полета Ю.А. Гагарина",
      "desc":  "Стоимость:",
      "price": "249",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-1",
      "datayear": "data-year = year-2",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5010-0008"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2001/gagarin.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2001/2RU01-2.jpg",
      "md": "./img/other/spmd-m.jpg",
      "title": "2 рубля 2001",
      "text": "40-летие космического полета Ю.А. Гагарина",
      "desc":  "Стоимость:",
      "price": "119",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-1",
      "datayear": "data-year = year-2",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5010-0008"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2012/2RU12-1.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2012/2RU12-18.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "2 рубля 2012",
      "text": "Эмблема празднования",
      "desc":  "Стоимость:",
      "price": "99",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-2",
      "datayear": "data-year = year-3",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5710-0001"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2012/2RU12-2.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2012/2RU12-19.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "2 рубля 2012",
      "text": "Генерал-фельдмаршал М.И. Кутузов",
      "desc":  "Стоимость:",
      "price": "30",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-2",
      "datayear": "data-year = year-3",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5710-0002"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2012/2RU12-3.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2012/2RU12-19.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "2 рубля 2012",
      "text": "Генерал-фельдмаршал М.Б. Барклай де Толли",
      "desc":  "Стоимость:",
      "price": "30",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-2",
      "datayear": "data-year = year-3",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5710-0003"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2012/2RU12-4.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2012/2RU12-19.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "2 рубля 2012",
      "text": "Генерал от инфантерии П.И. Багратион",
      "desc":  "Стоимость:",
      "price": "30",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-2",
      "datayear": "data-year = year-3",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5710-0004"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2012/2RU12-5.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2012/2RU12-19.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "2 рубля 2012",
      "text": "Генерал от кавалерии Л.Л. Беннигсен",
      "desc":  "Стоимость:",
      "price": "30",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-2",
      "datayear": "data-year = year-3",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5710-0005"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2012/2RU12-6.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2012/2RU12-19.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "2 рубля 2012",
      "text": "Генерал-фельдмаршал П.Х. Витгенштейн",
      "desc":  "Стоимость:",
      "price": "30",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-2",
      "datayear": "data-year = year-3",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5710-0006"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2012/2RU12-7.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2012/2RU12-19.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "2 рубля 2012",
      "text": "Генерал-лейтенант Д.В. Давыдов",
      "desc":  "Стоимость:",
      "price": "30",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-2",
      "datayear": "data-year = year-3",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5710-0007"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2012/2RU12-8.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2012/2RU12-19.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "2 рубля 2012",
      "text": "Генерал от инфантерии Д.С. Дохтуров",
      "desc":  "Стоимость:",
      "price": "30",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-2",
      "datayear": "data-year = year-3",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5710-0008"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2012/2RU12-9.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2012/2RU12-19.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "2 рубля 2012",
      "text": "Штабс-ротмистр Н.А Дурова",
      "desc":  "Стоимость:",
      "price": "30",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-2",
      "datayear": "data-year = year-3",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5710-0009"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2012/2RU12-10.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2012/2RU12-19.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "2 рубля 2012",
      "text": "Генерал от инфантерии А.П. Ермолов",
      "desc":  "Стоимость:",
      "price": "30",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-2",
      "datayear": "data-year = year-3",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5710-0010"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2012/2RU12-11.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2012/2RU12-19.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "2 рубля 2012",
      "text": "Организатор партизанского движения Василиса Кожина",
      "desc":  "Стоимость:",
      "price": "30",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-2",
      "datayear": "data-year = year-3",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5710-0011"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2012/2RU12-12.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2012/2RU12-19.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "2 рубля 2012",
      "text": "Генерал-майор А.И Кутайсов",
      "desc":  "Стоимость:",
      "price": "30",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-2",
      "datayear": "data-year = year-3",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5710-0012"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2012/2RU12-13.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2012/2RU12-19.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "2 рубля 2012",
      "text": "Генерал от инфантерии М.А. Милорадович",
      "desc":  "Стоимость:",
      "price": "30",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-2",
      "datayear": "data-year = year-3",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5710-0013"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2012/2RU12-14.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2012/2RU12-19.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "2 рубля 2012",
      "text": "Генерал от инфантерии А.И. Остерман-Толстой",
      "desc":  "Стоимость:",
      "price": "30",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-2",
      "datayear": "data-year = year-3",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5710-0014"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2012/2RU12-15.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2012/2RU12-19.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "2 рубля 2012",
      "text": "Генерал от кавалерии Н.Н. Раевский",
      "desc":  "Стоимость:",
      "price": "30",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-2",
      "datayear": "data-year = year-3",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5710-0015"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2012/2RU12-16.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2012/2RU12-19.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "2 рубля 2012",
      "text": "Генерал от кавалерии М.И. Платов",
      "desc":  "Стоимость:",
      "price": "30",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-2",
      "datayear": "data-year = year-3",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5710-0016"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2012/2RU12-17.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2012/2RU12-19.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "2 рубля 2012",
      "text": "Император Александр I",
      "desc":  "Стоимость:",
      "price": "30",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-2",
      "datayear": "data-year = year-3",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5710-0017"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2017/2RU17-1.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2017/2RU17-3.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "2 рубля 2017",
      "text": "Город-герой Керчь",
      "desc":  "Стоимость:",
      "price": "139",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-3",
      "datayear": "data-year = year-4",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5710-0018"
    },
    {
      "img": "./img/coins/russia/yubilee/2ru/2017/2RU17-2.jpg",
      "imgrev": "./img/coins/russia/yubilee/2ru/2017/2RU17-3.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "2 рубля 2017",
      "text": "Город-герой Севастополь",
      "desc":  "Стоимость:",
      "price": "139",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-3",
      "datayear": "data-year = year-4",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5710-0019"
    }
    
  ]

  return json2ruyub;
}
export default json2ruyub;