function json5kopru(){

  const json5kopru=[
    {
      "img": "./img/coins/russia/regular/5kop/1997/97_5K_M.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/1997/97_5K_M_R.jpg",
      "md": "./img/other/m.png",
      "title": "5 копеек 1997",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "15",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/1997/97_5K_S.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/1997/97_5K_S_R.jpg",
      "md": "./img/other/sp.png",
      "title": "5 копеек 1997",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/1998/98_5K_M.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/1998/98_5K_M_R.jpg",
      "md": "./img/other/m.png",
      "title": "5 копеек 1998",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/1998/98_5K_S.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/1998/98_5K_S_R.jpg",
      "md": "./img/other/sp.png",
      "title": "5 копеек 1998",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/2000/00_5K_M.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/2000/00_5K_M_R.jpg",
      "md": "./img/other/m.png",
      "title": "5 копеек 2000",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "80",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/2000/00_5K_S.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/2000/00_5K_S_R.jpg",
      "md": "./img/other/sp.png",
      "title": "5 копеек 2000",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "150",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/2001/01_5K_M.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/2001/01_5K_M_R.jpg",
      "md": "./img/other/m.png",
      "title": "5 копеек 2001",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/2001/01_5K_S.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/2001/01_5K_S_R.jpg",
      "md": "./img/other/sp.png",
      "title": "5 копеек 2001",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/2002/02_5K_M.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/2002/02_5K_M_R.jpg",
      "md": "./img/other/m.png",
      "title": "5 копеек 2002",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/2002/02_5K_S.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/2002/02_5K_S_R.jpg",
      "md": "./img/other/sp.png",
      "title": "5 копеек 2002",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/2002/02_5K.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/2002/02_5K_R.jpg",
      "md": "./img/other/none.png",
      "title": "5 копеек 2002",
      "text": "Редкая",
      "desc":  "Стоимость:",
      "price": "1199",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/2003/03_5K_M.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/2003/03_5K_M_R.jpg",
      "md": "./img/other/m.png",
      "title": "5 копеек 2003",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/2003/03_5K_S.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/2003/03_5K_S_R.jpg",
      "md": "./img/other/sp.png",
      "title": "5 копеек 2003",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/2003/03_5K.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/2003/03_5K_R.jpg",
      "md": "./img/other/none.png",
      "title": "5 копеек 2003",
      "text": "Редкая",
      "desc":  "Стоимость:",
      "price": "1199",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/2004/04_5K_M.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/2004/04_5K_M_R.jpg",
      "md": "./img/other/m.png",
      "title": "5 копеек 2004",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "20",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/2004/04_5K_S.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/2004/04_5K_S_R.jpg",
      "md": "./img/other/sp.png",
      "title": "5 копеек 2004",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/2005/05_5K_M.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/2005/05_5K_M_R.jpg",
      "md": "./img/other/m.png",
      "title": "5 копеек 2005",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/2005/05_5K_S.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/2005/05_5K_S_R.jpg",
      "md": "./img/other/sp.png",
      "title": "5 копеек 2005",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/2006/06_5K_M.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/2006/06_5K_M_R.jpg",
      "md": "./img/other/m.png",
      "title": "5 копеек 2006",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/2006/06_5K_S.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/2006/06_5K_S_R.jpg",
      "md": "./img/other/sp.png",
      "title": "5 копеек 2006",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/2007/07_5K_M.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/2007/07_5K_M_R.jpg",
      "md": "./img/other/m.png",
      "title": "5 копеек 2007",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "20",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/2007/07_5K_S.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/2007/07_5K_S_R.jpg",
      "md": "./img/other/sp.png",
      "title": "5 копеек 2007",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/2008/08_5K_M.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/2008/08_5K_M_R.jpg",
      "md": "./img/other/m.png",
      "title": "5 копеек 2008",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "20",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/2008/08_5K_S.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/2008/08_5K_S_R.jpg",
      "md": "./img/other/sp.png",
      "title": "5 копеек 2008",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/2009/09_5K_M.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/2009/09_5K_M_R.jpg",
      "md": "./img/other/m.png",
      "title": "5 копеек 2009",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "60",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/2009/09_5K_S.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/2009/09_5K_S_R.jpg",
      "md": "./img/other/sp.png",
      "title": "5 копеек 2009",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "20",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    },
    {
      "img": "./img/coins/russia/regular/5kop/2014/14_5K_M.jpg",
      "imgrev": "./img/coins/russia/regular/5kop/2014/14_5K_M_R.jpg",
      "md": "./img/other/m.png",
      "title": "5 копеек 2014",
      "text": "Регулярный выпуск",
      "desc":  "Стоимость:",
      "price": "30",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "link": "https://cbr.ru/cash_circulation/coins/5k/"
    }
  ]
  return json5kopru;

}
export default json5kopru;