function json5ruyub(){
  const json5ruyub=[
    {
      "img": "./img/coins/russia/yubilee/5ru/2012/5RU12-1.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2012/5RU12-11.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2012",
      "text": "Сражение у Кульма",
      "desc":  "Стоимость:",
      "price": "150",
      "count": "4",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-2",
      "datayear": "data-year = year-1",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0008"
    },
    {
    "img": "./img/coins/russia/yubilee/5ru/2012/5RU12-2.jpg",
    "imgrev": "./img/coins/russia/yubilee/5ru/2012/5RU12-11.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "5 рублей 2012",
    "text": "Лейпцигское сражение",
    "desc":  "Стоимость:",
    "price": "150",
    "count": "5",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-1",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0009"
  },
  {
    "img": "./img/coins/russia/yubilee/5ru/2012/5RU12-3.jpg",
    "imgrev": "./img/coins/russia/yubilee/5ru/2012/5RU12-11.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "5 рублей 2012",
    "text": "Взятие Парижа",
    "desc":  "Стоимость:",
    "price": "150",
    "count": "6",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-1",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0010"
  },
  {
    "img": "./img/coins/russia/yubilee/5ru/2012/5RU12-4.jpg",
    "imgrev": "./img/coins/russia/yubilee/5ru/2012/5RU12-11.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "5 рублей 2012",
    "text": "Смоленское сражение",
    "desc":  "Стоимость:",
    "price": "150",
    "count": "1",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-1",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0002"
  },
  {
    "img": "./img/coins/russia/yubilee/5ru/2012/5RU12-5.jpg",
    "imgrev": "./img/coins/russia/yubilee/5ru/2012/5RU12-11.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "5 рублей 2012",
    "text": "Бородинское сражение",
    "desc":  "Стоимость:",
    "price": "150",
    "count": "5",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-1",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0003"
  },
  {
    "img": "./img/coins/russia/yubilee/5ru/2012/5RU12-6.jpg",
    "imgrev": "./img/coins/russia/yubilee/5ru/2012/5RU12-11.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "5 рублей 2012",
    "text": "Бой при Вязьме",
    "desc":  "Стоимость:",
    "price": "150",
    "count": "5",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-1",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0004"
  },
  {
    "img": "./img/coins/russia/yubilee/5ru/2012/5RU12-7.jpg",
    "imgrev": "./img/coins/russia/yubilee/5ru/2012/5RU12-11.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "5 рублей 2012",
    "text": "Малоярославецкое сражение",
    "desc":  "Стоимость:",
    "price": "150",
    "count": "2",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-1",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0005"
  },
  {
    "img": "./img/coins/russia/yubilee/5ru/2012/5RU12-8.jpg",
    "imgrev": "./img/coins/russia/yubilee/5ru/2012/5RU12-11.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "5 рублей 2012",
    "text": "Тарутинское сражение",
    "desc":  "Стоимость:",
    "price": "150",
    "count": "1",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-1",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0006"
  },
  {
    "img": "./img/coins/russia/yubilee/5ru/2012/5RU12-9.jpg",
    "imgrev": "./img/coins/russia/yubilee/5ru/2012/5RU12-11.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "5 рублей 2012",
    "text": "Cражение при Березине",
    "desc":  "Стоимость:",
    "price": "150",
    "count": "1",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-1",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0007"
  },
  {
    "img": "./img/coins/russia/yubilee/5ru/2012/5RU12-10.jpg",
    "imgrev": "./img/coins/russia/yubilee/5ru/2012/5RU12-11.jpg",
    "md": "./img/other/mmd.jpg",
    "title": "5 рублей 2012",
    "text": "Сражение при Красном",
    "desc":  "Стоимость:",
    "price": "150",
    "count": "3",
    "info": "В наличии",
    "color": "card__on",
    "dataseries": "data-series = series-2",
    "datayear": "data-year = year-1",
    "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0001"
  },
  {
      "img": "./img/coins/russia/yubilee/5ru/2014/5RU14-1.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2014/5RU14-13.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2014",
      "text": "Восточно-Прусская операция",
      "desc":  "Стоимость:",
      "price": "59",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-4",
      "datayear": "data-year = year-2",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0025"
    },
  {
      "img": "./img/coins/russia/yubilee/5ru/2014/5RU14-2.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2014/5RU14-13.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2014",
      "text": "Венская операция",
      "desc":  "Стоимость:",
      "price": "59",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-4",
      "datayear": "data-year = year-2",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0026"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2014/5RU14-3.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2014/5RU14-13.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2014",
      "text": "Берлинская операция",
      "desc":  "Стоимость:",
      "price": "200",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-4",
      "datayear": "data-year = year-2",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0027"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2014/5RU14-4.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2014/5RU14-13.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2014",
      "text": "Пражская операция",
      "desc":  "Стоимость:",
      "price": "59",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-4",
      "datayear": "data-year = year-2",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0028"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2014/5RU14-7.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2014/5RU14-13.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2014",
      "text": "Прибалтийская операция",
      "desc":  "Стоимость:",
      "price": "59",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-4",
      "datayear": "data-year = year-2",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0021"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2014/5RU14-8.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2014/5RU14-13.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2014",
      "text": "Операция по освобождению Карелии и Заполярья",
      "desc":  "Стоимость:",
      "price": "59",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-4",
      "datayear": "data-year = year-2",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0022"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2014/5RU14-5.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2014/5RU14-13.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2014",
      "text": "Будапештская операция",
      "desc":  "Стоимость:",
      "price": "59",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-4",
      "datayear": "data-year = year-2",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0023"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2014/5RU14-6.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2014/5RU14-13.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2014",
      "text": "Висло-Одерская операция",
      "desc":  "Стоимость:",
      "price": "59",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-4",
      "datayear": "data-year = year-2",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0024"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2014/5RU14-9.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2014/5RU14-13.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2014",
      "text": "Битва за Ленинград",
      "desc":  "Стоимость:",
      "price": "59",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-4",
      "datayear": "data-year = year-2",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0017"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2014/5RU14-11.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2014/5RU14-13.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2014",
      "text": "Белорусская операция",
      "desc":  "Стоимость:",
      "price": "59",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-4",
      "datayear": "data-year = year-2",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0018"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2014/5RU14-12.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2014/5RU14-13.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2014",
      "text": "Львовско-Сандомирская операция",
      "desc":  "Стоимость:",
      "price": "59",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-4",
      "datayear": "data-year = year-2",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0019"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2014/5RU14-10.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2014/5RU14-13.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2014",
      "text": "Ясско-Кишиневская операция",
      "desc":  "Стоимость:",
      "price": "59",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-4",
      "datayear": "data-year = year-2",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0020"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2014/5RU14-14.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2014/5RU14-13.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2014",
      "text": "Курская битва",
      "desc":  "Стоимость:",
      "price": "59",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-4",
      "datayear": "data-year = year-2",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0014"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2014/5RU14-15.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2014/5RU14-13.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2014",
      "text": "Битва за Днепр",
      "desc":  "Стоимость:",
      "price": "59",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-4",
      "datayear": "data-year = year-2",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0015"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2014/5RU14-16.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2014/5RU14-13.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2014",
      "text": "Днепровско-Карпатская операция",
      "desc":  "Стоимость:",
      "price": "59",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-4",
      "datayear": "data-year = year-2",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0016"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2014/5RU14-17.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2014/5RU14-13.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2014",
      "text": "Битва под Москвой",
      "desc":  "Стоимость:",
      "price": "59",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-4",
      "datayear": "data-year = year-2",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0011"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2014/5RU14-18.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2014/5RU14-13.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2014",
      "text": "Сталинградская битва",
      "desc":  "Стоимость:",
      "price": "59",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-4",
      "datayear": "data-year = year-2",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0012"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2014/5RU14-19.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2014/5RU14-13.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2014",
      "text": "Битва за Кавказ",
      "desc":  "Стоимость:",
      "price": "59",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-4",
      "datayear": "data-year = year-2",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0013"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2015/5RU15-1.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2015/5RU15-7.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2015",
      "text": "170-летие Русского географического общества",
      "desc":  "Стоимость:",
      "price": "39",
      "count": "1",
      "info": "Отсутствует",
      "color": "card__on",
      "dataseries": "data-series = series-1",
      "datayear": "data-year = year-3",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0029"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2015/5RU15-2.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2015/5RU15-7.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2015",
      "text": "Оборона Севастополя",
      "desc":  "Стоимость:",
      "price": "59",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-4",
      "datayear": "data-year = year-3",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0030"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2015/5RU15-3.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2015/5RU15-7.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2015",
      "text": "Оборона Аджимушкайских каменоломен",
      "desc":  "Стоимость:",
      "price": "59",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-4",
      "datayear": "data-year = year-3",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0031"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2015/5RU15-4.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2015/5RU15-7.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2015",
      "text": "Керченско-Эльтигенская десантная операция",
      "desc":  "Стоимость:",
      "price": "59",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-4",
      "datayear": "data-year = year-3",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0032"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2015/5RU15-5.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2015/5RU15-7.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2015",
      "text": "Крымская стратегическая наступательная операция",
      "desc":  "Стоимость:",
      "price": "59",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-4",
      "datayear": "data-year = year-3",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0033"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2015/5RU15-6.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2015/5RU15-7.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2015",
      "text": "Партизаны и подпольщики Крыма",
      "desc":  "Стоимость:",
      "price": "59",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-4",
      "datayear": "data-year = year-3",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0034"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2016/5RU16-1.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2016/5RU16-16.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2016",
      "text": "150-летие основания Русского исторического общества",
      "desc":  "Стоимость:",
      "price": "10",
      "count": "12",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-1",
      "datayear": "data-year = year-4",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0049"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2016/5RU16-2.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2016/5RU16-16.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2016",
      "text": "Киев. 6.11.1943 г.",
      "desc":  "Стоимость:",
      "price": "25",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-3",
      "datayear": "data-year = year-4",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0035"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2016/5RU16-3.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2016/5RU16-16.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2016",
      "text": "Минск. 3.07.1944 г.",
      "desc":  "Стоимость:",
      "price": "25",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-3",
      "datayear": "data-year = year-4",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0036"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2016/5RU16-4.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2016/5RU16-16.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2016",
      "text": "Вильнюс. 13.07.1944 г.",
      "desc":  "Стоимость:",
      "price": "25",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-3",
      "datayear": "data-year = year-4",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0037"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2016/5RU16-5.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2016/5RU16-16.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2016",
      "text": "Кишинев. 24.08.1944 г.",
      "desc":  "Стоимость:",
      "price": "25",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-3",
      "datayear": "data-year = year-4",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0038"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2016/5RU16-6.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2016/5RU16-16.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2016",
      "text": "Бухарест. 31.08.1944 г.",
      "desc":  "Стоимость:",
      "price": "25",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-3",
      "datayear": "data-year = year-4",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0039"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2016/5RU16-7.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2016/5RU16-16.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2016",
      "text": "Таллин. 22.09.1944 г.",
      "desc":  "Стоимость:",
      "price": "25",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-3",
      "datayear": "data-year = year-4",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0040"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2016/5RU16-8.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2016/5RU16-16.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2016",
      "text": "Рига. 15.10.1944 г.",
      "desc":  "Стоимость:",
      "price": "25",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-3",
      "datayear": "data-year = year-4",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0041"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2016/5RU16-9.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2016/5RU16-16.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2016",
      "text": "Белград. 20.10.1944 г.",
      "desc":  "Стоимость:",
      "price": "25",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-3",
      "datayear": "data-year = year-4",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0042"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2016/5RU16-10.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2016/5RU16-16.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2016",
      "text": "Варшава. 17.01.1945 г.",
      "desc":  "Стоимость:",
      "price": "25",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-3",
      "datayear": "data-year = year-4",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0043"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2016/5RU16-11.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2016/5RU16-16.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2016",
      "text": "Братислава. 4.04.1945 г.",
      "desc":  "Стоимость:",
      "price": "25",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-3",
      "datayear": "data-year = year-4",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0044"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2016/5RU16-12.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2016/5RU16-16.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2016",
      "text": "Будапешт. 13.02.1945 г.",
      "desc":  "Стоимость:",
      "price": "25",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-3",
      "datayear": "data-year = year-4",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0045"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2016/5RU16-13.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2016/5RU16-16.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2016",
      "text": "Вена. 13.04.1945 г.",
      "desc":  "Стоимость:",
      "price": "25",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-3",
      "datayear": "data-year = year-4",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0046"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2016/5RU16-14.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2016/5RU16-16.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2016",
      "text": "Берлин. 2.05.1945 г.",
      "desc":  "Стоимость:",
      "price": "25",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-3",
      "datayear": "data-year = year-4",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0047"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2016/5RU16-15.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2016/5RU16-16.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2016",
      "text": "Прага. 9.05.1945 г.",
      "desc":  "Стоимость:",
      "price": "25",
      "count": "0",
      "info": "Отсутствует",
      "color": "card__off",
      "dataseries": "data-series = series-3",
      "datayear": "data-year = year-4",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0048"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2019/crimebridg.jpg",
      "imgrev": "./img/coins/russia/yubilee/5ru/2019/5RU19-2.jpg",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2019",
      "text": "Воссоединение Крыма с Россией",
      "desc":  "Стоимость:",
      "price": "50",
      "count": "1",
      "info": "В наличии",
      "color": "card__on",
      "dataseries": "data-series = series-1",
      "datayear": "data-year = year-5",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0050"
    },
    {
      "img": "./img/coins/russia/yubilee/5ru/2020/5RU20-1.png",
      "imgrev": "./img/coins/russia/yubilee/5ru/2020/5RU20-2.png",
      "md": "./img/other/mmd.jpg",
      "title": "5 рублей 2020",
      "text": "Курильская десантная операция",
      "desc":  "Стоимость:",
      "price": "20",
      "count": "0",
      "info": "В наличии",
      "color": "card__off",
      "dataseries": "data-series = series-4",
      "datayear": "data-year = year-6",
      "link": "https://cbr.ru/cash_circulation/memorable_coins/coins_base/ShowCoins/?cat_num=5712-0051"
    }
  ]

  return json5ruyub;
}
export default json5ruyub;